import { Card, CardContent } from '../components/ui/Card';
import { ShieldAlert } from 'lucide-react';

export default function About() {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <h2 className="text-3xl font-bold text-slate-900">About MedPredict AI</h2>
        <p className="text-lg text-slate-600">A demonstration platform for machine learning applications in healthcare.</p>
      </div>

      <div className="bg-red-50 border-l-4 border-red-500 p-6 rounded-r-md">
        <div className="flex items-start space-x-3">
          <ShieldAlert className="h-6 w-6 text-red-600 shrink-0 mt-1" />
          <div>
            <h3 className="text-red-800 font-bold text-lg mb-2">CRITICAL DISCLAIMER</h3>
            <p className="text-red-700 text-sm leading-relaxed">
              This application is designed for educational, research, and demonstration purposes only. 
              The predictions generated by these models are NOT substitutes for professional medical advice, 
              diagnosis, or treatment. Never disregard professional medical advice or delay in seeking it 
              because of something you have read on this application. Always consult with a qualified 
              healthcare provider regarding any medical condition.
            </p>
          </div>
        </div>
      </div>

      <Card>
        <CardContent className="p-8 space-y-6">
          <div>
            <h3 className="text-xl font-bold text-slate-900 mb-3 border-b pb-2">Project Overview</h3>
            <p className="text-slate-600 leading-relaxed">
              MedPredict AI integrates modern web technologies with machine learning to provide a seamless interface for predictive healthcare analytics. The platform currently supports prediction models for Heart Disease, Diabetes, and Breast Cancer, utilizing datasets curated and pre-processed for high accuracy.
            </p>
          </div>

          <div>
            <h3 className="text-xl font-bold text-slate-900 mb-3 border-b pb-2">Technology Stack</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
              <div className="bg-slate-50 p-4 rounded-md text-center border border-slate-100">
                <span className="font-semibold text-slate-800">Frontend</span>
                <p className="text-xs text-slate-500 mt-1">React, TypeScript, Tailwind CSS</p>
              </div>
              <div className="bg-slate-50 p-4 rounded-md text-center border border-slate-100">
                <span className="font-semibold text-slate-800">Backend</span>
                <p className="text-xs text-slate-500 mt-1">Python, FastAPI</p>
              </div>
              <div className="bg-slate-50 p-4 rounded-md text-center border border-slate-100">
                <span className="font-semibold text-slate-800">ML Models</span>
                <p className="text-xs text-slate-500 mt-1">Scikit-learn, XGBoost</p>
              </div>
              <div className="bg-slate-50 p-4 rounded-md text-center border border-slate-100">
                <span className="font-semibold text-slate-800">Data</span>
                <p className="text-xs text-slate-500 mt-1">Pandas, NumPy</p>
              </div>
            </div>
          </div>

          <div>
            <h3 className="text-xl font-bold text-slate-900 mb-3 border-b pb-2">Datasets & Algorithms</h3>
            <ul className="list-disc pl-5 space-y-2 text-slate-600 text-sm">
              <li><strong>Heart Disease:</strong> Based on the UCI Heart Disease dataset. Features 13 clinical attributes.</li>
              <li><strong>Diabetes:</strong> Based on the Pima Indians Diabetes Database. Features 8 diagnostic measurements.</li>
              <li><strong>Breast Cancer:</strong> Based on the Breast Cancer Wisconsin (Diagnostic) dataset. Features 30 numerical attributes computed from cell nuclei.</li>
            </ul>
            <p className="text-slate-600 text-sm mt-4">
              The system employs various algorithms including Logistic Regression, Support Vector Machines (SVC), Random Forest, and XGBoost, dynamically selecting the best performing model for each specific disease category based on rigorous testing and validation metrics.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
