import { cn } from '../utils/cn';
import type { PredictionResult as IPredictionResult } from '../types';
import { Button } from './ui/Button';
import { useNavigate } from 'react-router-dom';

export function PredictionResult({ result, onReset }: { result: IPredictionResult; onReset: () => void }) {
  const navigate = useNavigate();
  const isPositive = result.prediction === 1;
  const color = isPositive ? 'text-red-500' : 'text-green-500';
  const bgColor = isPositive ? 'bg-red-50' : 'bg-green-50';
  const progressColor = isPositive ? 'stroke-red-500' : 'stroke-green-500';

  return (
    <div className={cn("rounded-lg border p-8 flex flex-col items-center justify-center space-y-6", bgColor)}>
      <h2 className="text-2xl font-bold text-slate-800">{result.disease} Prediction Result</h2>
      
      <div className="relative w-48 h-48 flex items-center justify-center">
        <svg className="absolute inset-0 w-full h-full transform -rotate-90">
          <circle cx="96" cy="96" r="88" className="stroke-slate-200" strokeWidth="12" fill="none" />
          <circle cx="96" cy="96" r="88" className={cn("transition-all duration-1000 ease-out", progressColor)} strokeWidth="12" fill="none" strokeDasharray={2 * Math.PI * 88} strokeDashoffset={2 * Math.PI * 88 * (1 - result.probability)} />
        </svg>
        <div className="flex flex-col items-center">
          <span className={cn("text-4xl font-bold", color)}>{(result.probability * 100).toFixed(1)}%</span>
          <span className="text-sm text-slate-500">Probability</span>
        </div>
      </div>

      <div className="text-center space-y-2">
        <p className="text-xl font-semibold">
          Result: <span className={color}>{result.label}</span>
        </p>
        <p className="text-sm text-slate-600">Model used: {result.model}</p>
      </div>

      <div className="max-w-md text-center p-4 bg-white/60 rounded-md border border-slate-200">
        <p className="text-xs text-slate-500 uppercase font-semibold mb-1">Medical Disclaimer</p>
        <p className="text-sm text-slate-700">This result is generated by a machine learning model and is NOT a medical diagnosis. Please consult a qualified healthcare professional.</p>
      </div>

      <div className="flex space-x-4 mt-4">
        <Button onClick={onReset} variant="outline">New Prediction</Button>
        <Button onClick={() => navigate('/history')}>View History</Button>
      </div>
    </div>
  );
}
