import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { PredictionResult } from '../../components/PredictionResult';
import type { DiabetesInput, PredictionResult as IPredictionResult } from '../../types';
import { predictApi } from '../../services/api';
import { Info } from 'lucide-react';

export default function DiabetesPrediction() {
  const [formData, setFormData] = useState<DiabetesInput>({
    Pregnancies: 0, Glucose: 120, BloodPressure: 70, SkinThickness: 20, Insulin: 79, BMI: 25.0, DiabetesPedigreeFunction: 0.5, Age: 30
  });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<IPredictionResult | null>(null);
  const [error, setError] = useState('');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: parseFloat(value) || 0 }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const res = await predictApi.predictDiabetes(formData);
      setResult(res);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to get prediction');
    } finally {
      setLoading(false);
    }
  };

  if (result) {
    return <PredictionResult result={result} onReset={() => setResult(null)} />;
  }

  return (
    <div className="max-w-4xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle>Diabetes Prediction</CardTitle>
          <CardDescription>Enter patient diagnostic measurements to predict the onset of diabetes.</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <Input label="Pregnancies" name="Pregnancies" type="number" min="0" max="20" value={formData.Pregnancies} onChange={handleChange} required />
              <Input label="Glucose (mg/dL)" name="Glucose" type="number" min="0" max="300" value={formData.Glucose} onChange={handleChange} required />
              <Input label="Blood Pressure (mm Hg)" name="BloodPressure" type="number" min="0" max="200" value={formData.BloodPressure} onChange={handleChange} required />
              <Input label="Skin Thickness (mm)" name="SkinThickness" type="number" min="0" max="100" value={formData.SkinThickness} onChange={handleChange} required />
              <Input label="Insulin (µU/ml)" name="Insulin" type="number" min="0" max="1000" value={formData.Insulin} onChange={handleChange} required />
              <Input label="BMI" name="BMI" type="number" step="0.1" min="0" max="70" value={formData.BMI} onChange={handleChange} required />
              <Input label="Diabetes Pedigree Function" name="DiabetesPedigreeFunction" type="number" step="0.001" min="0" max="3" value={formData.DiabetesPedigreeFunction} onChange={handleChange} required />
              <Input label="Age" name="Age" type="number" min="1" max="120" value={formData.Age} onChange={handleChange} required />
            </div>

            {error && <div className="text-red-500 font-medium bg-red-50 p-3 rounded-md">{error}</div>}

            <div className="bg-yellow-50 border border-yellow-200 rounded-md p-4 text-sm text-yellow-800 flex items-start">
              <Info className="h-5 w-5 mr-2 shrink-0 mt-0.5" />
              <p><strong>Medical Disclaimer:</strong> This result is generated by a machine learning model and is NOT a medical diagnosis. Please consult a qualified healthcare professional.</p>
            </div>

            <Button type="submit" isLoading={loading} className="w-full">Run Prediction</Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
